In [1]:
%load_ext autoreload
%autoreload 1

In [2]:
import sys
sys.path.append('..')

In [3]:
%aimport lab2
%aimport utils

# Теорема про неявну функцію

In [24]:
solver = lab2.ImplicitFunctionSolver.from_string("x + sinh(x) - sin(y) - y = 0",
                                                 "z + exp(z) - x -ln(1+x) - 1 = 0",
                                                 (0, 0, 0))

F('x', 'y', 'z') = x - y - sin(y) + sinh(x)
G('x', 'y', 'z') = -x + z + exp(z) - log(x + 1) - 1



In [25]:
p, d1, d2, d3 = solver.solve(3)

Finding dependent variables.
⎡cosh(x) + 1  -cos(y) - 1⎤
⎢                        ⎥
⎢       1                ⎥
⎢-1 - ─────        0     ⎥
⎣     x + 1              ⎦
det = -(-1 - 1/(x + 1))*(-cos(y) - 1) = -4
Accepted z.

Calculating parametrisation diff.
r = [f(z)  g(z)  z]

f(z) - g(z) - sin(g(z)) + sinh(f(z)) = 0
z - f(z) + exp(z) - log(f(z) + 1) - 1 = 0

Step  1
r' =[f'(z)  g'(z)  1]
-cos(g(z))*Derivative(g(z), z) + cosh(f(z))*Derivative(f(z), z) + Derivative(f(z), z) - Derivative(g(z), z) = 0
exp(z) - Derivative(f(z), z) + 1 - Derivative(f(z), z)/(f(z) + 1) = 0

Solving system.
2*f'(0) - 2*g'(0) = 0
2 - 2*f'(0) = 0

Solution  {f'(z): 1, g'(z): 1}

Step  2
r'' =[f''(z)  g''(z)  0]
sin(g(z))*Derivative(g(z), z)**2 - cos(g(z))*Derivative(g(z), (z, 2)) + sinh(f(z))*Derivative(f(z), z)**2 + cosh(f(z))*Derivative(f(z), (z, 2)) + Derivative(f(z), (z, 2)) - Derivative(g(z), (z, 2)) = 0
exp(z) - Derivative(f(z), (z, 2)) - Derivative(f(z), (z, 2))/(f(z) + 1) + Derivative(f(z), z)**2/(f(z) + 1

In [26]:
p, d1, d2, d3

# Тригранник Френе

In [27]:
import numpy as np
from IPython.display import Math

In [28]:
eq_builder = utils.EqBuilder(np.array(list(p)).astype('float64'),
                             np.array(list(d1)).astype('float64'),
                             np.array(list(d2)).astype('float64'),
                             np.array(list(d3)).astype('float64'))

## Орти

### Дотична

In [29]:
utils.tangent(eq_builder.d1)

array([0.57735028, 0.57735028, 0.57735028])

### Бінормаль

In [30]:
utils.binormal(eq_builder.d1, eq_builder.d2)

array([-0.70710678,  0.70710678,  0.        ])

### Головна нормаль

In [31]:
utils.normal(eq_builder.d1, eq_builder.d2)

array([ 0.4082483,  0.4082483, -0.8164966])

## Рівнняння ребер тригранника Френе

### Дотична

In [32]:
Math(eq_builder.tangent_eq())

<IPython.core.display.Math object>

### Бінормаль

In [33]:
Math(eq_builder.binormal_eq())

<IPython.core.display.Math object>

### Головна нормаль

In [34]:
Math(eq_builder.normal_eq())

<IPython.core.display.Math object>

## Рівняння граней тригранника Френе

### Нормальна площина

In [35]:
print(eq_builder.normal_plane())

0.577*x + 0.577*y + 0.577*z = 0


### Стична площина

In [36]:
print(eq_builder.osculating_plane())

-0.707*x + 0.707*y = 0


### Спрямна площина

In [37]:
print(eq_builder.rectifying_plane())

0.408*x + 0.408*y - 0.817*z = 0


# Кривина і скрут

In [38]:
utils.curvature(eq_builder.d1, eq_builder.d2)

In [39]:
utils.torsion(eq_builder.d1, eq_builder.d2, eq_builder.d3)

# Стичне коло

### Центр

In [20]:
center, radius = utils.osculating_circle(eq_builder.p,
                                         eq_builder.d1,
                                         eq_builder.d2)

In [21]:
center

array([ 2.00000002e+00, -1.71142716e-08, -1.00000003e+00])

### Радіус

In [22]:
radius

In [23]:
print(eq_builder.osculating_circle())

(x - 2.000)**2 + (y - -1.71)**2 + (z - -1.00)**2 = 6.0000000000000036
-0.577*x + 0.577*y - 0.577*z + 0.577 = 0
