In [1]:
%load_ext autoreload
%autoreload 1

In [2]:
import sys
sys.path.append('..')

In [32]:
%aimport lab2
%aimport utils

# Теорема про неявну функцію

In [29]:
solver = lab2.ImplicitFunctionSolver.from_string("x**2 + z**2 -y**2 - 1 = 0",
                                                 "- y**2 + 2*x - z  = 0",
                                                 (1, 1, 1))

F('x', 'y', 'z') = x**2 - y**2 + z**2 - 1
G('x', 'y', 'z') = 2*x - y**2 - z



In [30]:
p, d1, d2, d3 = solver.solve(3)

Finding dependent variables.
⎡2⋅x  -2⋅y⎤
⎢         ⎥
⎣ 2   -2⋅y⎦
det = -4*x*y + 4*y = 0

⎡2⋅x  2⋅z⎤
⎢        ⎥
⎣ 2   -1 ⎦
det = -2*x - 4*z = -6
Accepted y.

Calculating parametrisation diff.
r = [f(y)  y  g(y)]

-y**2 + f(y)**2 + g(y)**2 - 1 = 0
-y**2 + 2*f(y) - g(y) = 0

Step  1
r' =[f'(y)  1  g'(y)]
-2*y + 2*f(y)*Derivative(f(y), y) + 2*g(y)*Derivative(g(y), y) = 0
-2*y + 2*Derivative(f(y), y) - Derivative(g(y), y) = 0

Solving system.
2*f'(1) + 2*g'(1) - 2 = 0
2*f'(1) - g'(1) - 2 = 0

Solution  {f'(y): 1, g'(y): 0}

Step  2
r'' =[f''(y)  0  g''(y)]
2*f(y)*Derivative(f(y), (y, 2)) + 2*g(y)*Derivative(g(y), (y, 2)) + 2*Derivative(f(y), y)**2 + 2*Derivative(g(y), y)**2 - 2 = 0
2*Derivative(f(y), (y, 2)) - Derivative(g(y), (y, 2)) - 2 = 0

Solving system.
2*f''(1) + 2*g''(1) = 0
2*f''(1) - g''(1) - 2 = 0

Solution  {f''(y): 2/3, g''(y): -2/3}

Step  3
r''' =[f'''(y)  0  g'''(y)]
2*f(y)*Derivative(f(y), (y, 3)) + 2*g(y)*Derivative(g(y), (y, 3)) + 6*Derivative(f(y), y)*Derivative(f(y), (y

In [31]:
p, d1, d2, d3

# Тригранник Френе

In [62]:
import numpy as np
from IPython.display import Math

In [57]:
eq_builder = utils.EqBuilder(np.array(list(p)).astype('float64'),
                             np.array(list(d1)).astype('float64'),
                             np.array(list(d2)).astype('float64'),
                             np.array(list(d3)).astype('float64'))

## Орти

### Дотична

In [58]:
utils.tangent(eq_builder.d1)

array([0.70710679, 0.70710679, 0.        ])

### Бінормаль

In [59]:
utils.binormal(eq_builder.d1, eq_builder.d2)

array([-0.57735027,  0.57735027, -0.57735027])

### Головна нормаль

In [60]:
utils.normal(eq_builder.d1, eq_builder.d2)

array([ 0.4082483 , -0.4082483 , -0.81649659])

## Рівнняння ребер тригранника Френе

### Дотична

In [63]:
Math(eq_builder.tangent_eq())

<IPython.core.display.Math object>

### Бінормаль

In [64]:
Math(eq_builder.binormal_eq())

<IPython.core.display.Math object>

### Головна нормаль

In [65]:
Math(eq_builder.normal_eq())

<IPython.core.display.Math object>

## Рівняння граней тригранника Френе

### Нормальна площина

In [66]:
print(eq_builder.normal_plane())

0.707*x + 0.707*y - 1.41 = 0


### Стична площина

In [67]:
print(eq_builder.osculating_plane())

-0.577*x + 0.577*y - 0.577*z + 0.577 = 0


### Спрямна площина

In [68]:
print(eq_builder.rectifying_plane())

0.408*x - 0.408*y - 0.817*z + 0.817 = 0


# Кривина і скрут

In [74]:
utils.curvature(eq_builder.d1, eq_builder.d2)

In [75]:
utils.torsion(eq_builder.d1, eq_builder.d2, eq_builder.d3)

# Стичне коло

### Центр

In [79]:
center, radius = utils.osculating_circle(eq_builder.p,
                                         eq_builder.d1,
                                         eq_builder.d2)

In [80]:
center

array([ 2.00000002e+00, -1.71142716e-08, -1.00000003e+00])

### Радіус

In [81]:
radius

In [85]:
print(eq_builder.osculating_circle())

(x - 2.000)**2 + (y - -1.71)**2 + (z - -1.00)**2 = 2.4494897427831788
-0.577*x + 0.577*y - 0.577*z + 0.577 = 0
